'use client'

import { motion } from 'motion/react'
import { Github, Twitter, Linkedin } from 'lucide-react'

const socialLinks = [
  {
    name: 'GitHub',
    url: 'https://github.com/eldadfux',
    icon: Github,
  },
  {
    name: 'Twitter',
    url: 'https://twitter.com/eldadfux',
    icon: Twitter,
  },
  {
    name: 'LinkedIn',
    url: 'https://linkedin.com/in/eldadfux',
    icon: Linkedin,
  },
]

export function FooterSection() {
  return (
    <footer className="py-24 border-t border-black/10">
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        whileInView={{ opacity: 1, y: 0 }}
        viewport={{ once: true, margin: '-100px' }}
        transition={{ duration: 0.6, ease: [0.22, 1, 0.36, 1] }}
        className="flex flex-col md:flex-row justify-between items-start md:items-center gap-8"
      >
        <div className="space-y-2">
          <p
            className="text-2xl font-bold"
            style={{ fontFamily: 'JetBrains Mono, monospace' }}
          >
            Eldad Fux
          </p>
        </div>

        <div className="flex gap-3">
          {socialLinks.map((link, index) => {
            const Icon = link.icon
            return (
              <motion.a
                key={link.name}
                href={link.url}
                target="_blank"
                rel="noopener noreferrer"
                initial={{ opacity: 0, y: 10 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{
                  duration: 0.4,
                  delay: 0.2 + index * 0.05,
                  ease: [0.22, 1, 0.36, 1],
                }}
                whileHover={{ y: -2 }}
                whileTap={{ scale: 0.95 }}
                className="relative group"
                aria-label={link.name}
              >
                <div className="w-11 h-11 bg-black/5 group-hover:bg-black/10 transition-all duration-300 flex items-center justify-center">
                  <Icon className="w-4 h-4 text-black/60 group-hover:text-black transition-colors duration-300" />
                </div>
                <div className="absolute inset-0 border border-black/10 group-hover:border-black/30 transition-colors duration-300 pointer-events-none" />
              </motion.a>
            )
          })}
        </div>
      </motion.div>

      <motion.div
        initial={{ opacity: 0 }}
        whileInView={{ opacity: 1 }}
        viewport={{ once: true }}
        transition={{ duration: 0.6, delay: 0.4, ease: [0.22, 1, 0.36, 1] }}
        className="mt-16 pt-8 border-t border-black/5 space-y-4"
      >
        <p
          className="text-xs text-black/30 tracking-[0.15em] uppercase"
          style={{ fontFamily: 'JetBrains Mono, monospace' }}
        >
          © {new Date().getFullYear()}
        </p>
        <p className="text-xs text-black/30 font-light">
          Generated by{' '}
          <a
            href="https://imagine.dev"
            target="_blank"
            rel="noopener noreferrer"
            className="hover:text-black/50 transition-colors duration-300 underline decoration-black/20"
          >
            Imagine.dev
          </a>{' '}
          · Powered by{' '}
          <a
            href="https://appwrite.io"
            target="_blank"
            rel="noopener noreferrer"
            className="hover:text-black/50 transition-colors duration-300 underline decoration-black/20"
          >
            Appwrite
          </a>
        </p>
      </motion.div>
    </footer>
  )
}
