'use client'

import { motion } from 'motion/react'
import { FaGithub, FaXTwitter, FaLinkedin } from 'react-icons/fa6'

const socialLinks = [
  { name: 'GitHub', url: 'https://github.com/eldadfux', icon: FaGithub },
  { name: 'X', url: 'https://twitter.com/eldadfux', icon: FaXTwitter },
  { name: 'LinkedIn', url: 'https://linkedin.com/in/eldadfux', icon: FaLinkedin },
]

export function FooterSection() {
  return (
    <footer className="py-20 md:py-24 px-6 md:px-12 lg:px-20 border-t border-[#2a2825]">
      <div className="max-w-5xl mx-auto flex flex-col md:flex-row md:items-center md:justify-between gap-10">
        <motion.div
          initial={{ opacity: 0, y: 12 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5 }}
          className="flex flex-wrap items-center gap-6"
        >
          <p
            className="text-xl font-semibold text-[#e6e2db]"
            style={{ fontFamily: 'Fraunces, serif' }}
          >
            Eldad Fux
          </p>
          <div className="flex gap-4">
            {socialLinks.map((link) => {
              const Icon = link.icon
              return (
                <a
                  key={link.name}
                  href={link.url}
                  target="_blank"
                  rel="noopener noreferrer"
                  aria-label={link.name}
                  className="text-[#5a5652] hover:text-[#2dd4bf] transition-colors p-1.5 -m-1.5 rounded-lg hover:bg-[#161412]"
                >
                  <Icon className="w-5 h-5" />
                </a>
              )
            })}
          </div>
        </motion.div>
        <motion.p
          initial={{ opacity: 0 }}
          whileInView={{ opacity: 1 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5, delay: 0.1 }}
          className="text-[11px] text-[#5a5652] tracking-[0.12em] uppercase"
          style={{ fontFamily: 'JetBrains Mono, monospace' }}
        >
          Generated by{' '}
          <a
            href="https://imagine.dev"
            target="_blank"
            rel="noopener noreferrer"
            className="text-[#8a8580] hover:text-[#2dd4bf] transition-colors"
          >
            Imagine
          </a>
          , powered by{' '}
          <a
            href="https://appwrite.io"
            target="_blank"
            rel="noopener noreferrer"
            className="text-[#8a8580] hover:text-[#2dd4bf] transition-colors"
          >
            Appwrite
          </a>
        </motion.p>
      </div>
    </footer>
  )
}
